spring:
  application:
    name: Performance-Optimization-Service-test
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:perfdbtest
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    enabled: false

management:
  health:
    redis:
      enabled: false

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

